# Generated by Django 6.0.3 on 2026-03-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'Regular User'), ('guest', 'Guest')], default='user', max_length=10),
        ),
    ]
